apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackers-organized
  labels:
    app: hackers-organized
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackers-organized
  template:
    metadata:
      name: hackers-organized
      labels:
        app: hackers-organized
    spec:
      containers:
        - name: hackers-organized
          image: ldonleycb/hackers-organized:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ho-cm
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
